name: generate player movement animation

on:
  schedule:
    - cron: "0 */6 * * *"  # ejecuta cada 6 horas
  workflow_dispatch:
  push:
    branches:
    - master
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Generar la animación del jugador moviéndose entre las cajas
      - name: generate player movement animation
        uses: some-action/generate-player-movement@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-player-movement.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Subir la animación generada al repositorio
      - name: push player movement animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
